steps:
  # 1. Create a Docker image containing flink-bigquery-connector repo
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/dataproc-flink-bigquery-connector-nightly', '-f', 'cloudbuild/Dockerfile', '.']

# 2. Fetch maven and dependencies
  - name: 'gcr.io/$PROJECT_ID/dataproc-flink-bigquery-connector-nightly'
    id: 'init'
    waitFor: ['docker-build']
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/nightly.sh', 'init']
    env:
      - 'JAR_LOCATION=${_JAR_LOCATION}'
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'REGION=${_REGION}'
      - 'CLUSTER_NAME=${_CLUSTER_NAME}'
      - 'ARG_PROJECT_SIMPLE_TABLE=${_ARG_PROJECT_SIMPLE_TABLE}'
      - 'ARG_DATASET_SIMPLE_TABLE=${_ARG_DATASET_SIMPLE_TABLE}'
      - 'ARG_TABLE_SIMPLE_TABLE=${_ARG_TABLE_SIMPLE_TABLE}'

# 3. Start the e2e tests  
  - name: 'gcr.io/$PROJECT_ID/dataproc-flink-bigquery-connector-nightly'
    id: 'e2e-tests'
    waitFor: ['init']
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/nightly.sh', 'e2etest']
  

# Maximum test takes 20 mins, rest we run all in different clusters.
timeout: 1800s

options:
  machineType: 'N1_HIGHCPU_32'
