github:
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  labels:
    - flink
    - bigquery
    - connector
  autolink_jira: FLINK
  collaborators:
    - flinkbot

jobs:
  Nudge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
    steps:
      - uses: rpidanny/gha-pr-nudger@v1`
